CREATE TABLE IF NOT EXISTS`econtent_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cover` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `subTitle` varchar(255) NOT NULL DEFAULT '',
  `accessType` enum('free','acs','singleUse') NOT NULL DEFAULT 'free',
  `availableCopies` int(11) NOT NULL DEFAULT '1',
  `onOrderCopies` int(11) NOT NULL DEFAULT '0',
  `author` varchar(255) DEFAULT NULL,
  `author2` mediumtext,
  `description` mediumtext,
  `contents` mediumtext,
  `subject` mediumtext,
  `language` varchar(255) NOT NULL DEFAULT '',
  `publisher` varchar(255) NOT NULL DEFAULT '',
  `edition` varchar(255) NOT NULL DEFAULT '',
  `isbn` varchar(500) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `upc` varchar(255) DEFAULT NULL,
  `lccn` varchar(255) NOT NULL DEFAULT '',
  `series` varchar(255) NOT NULL DEFAULT '',
  `topic` mediumtext,
  `genre` mediumtext,
  `region` mediumtext,
  `era` varchar(255) NOT NULL DEFAULT '',
  `target_audience` varchar(255) NOT NULL DEFAULT '',
  `notes` mediumtext,
  `ilsId` varchar(255) DEFAULT NULL,
  `source` varchar(50) NOT NULL DEFAULT '',
  `sourceUrl` varchar(500) DEFAULT NULL,
  `purchaseUrl` varchar(500) DEFAULT NULL,
  `publishDate` varchar(100) DEFAULT NULL,
  `addedBy` int(11) NOT NULL DEFAULT '-1',
  `date_added` int(11) NOT NULL,
  `date_updated` int(11) DEFAULT NULL,
  `reviewedBy` int(11) NOT NULL DEFAULT '-1',
  `reviewStatus` enum('Not Reviewed','Approved','Rejected') NOT NULL DEFAULT 'Not Reviewed',
  `reviewDate` int(11) DEFAULT NULL,
  `reviewNotes` mediumtext,
  `trialTitle` tinyint(4) NOT NULL DEFAULT '0',
  `marcControlField` varchar(100) DEFAULT NULL,
  `collection` varchar(30) DEFAULT NULL,
  `marcRecord` mediumtext,
  `literary_form_full` varchar(30) DEFAULT NULL,
  `status` enum('active','deleted','archived') DEFAULT 'active',
  PRIMARY KEY (`id`),
  KEY `accessType` (`accessType`),
  KEY `source` (`source`),
  KEY `ECDateAdded` (`date_added`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `econtent_record_detection_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fieldSpec` varchar(100) DEFAULT NULL,
  `valueToMatch` varchar(100) DEFAULT NULL,
  `source` varchar(100) DEFAULT NULL,
  `accessType` varchar(30) DEFAULT NULL,
  `item_type` varchar(30) DEFAULT NULL,
  `add856FieldsAsExternalLinks` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `source` (`source`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `econtent_item` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'The id of the eContent item',
  `filename` varchar(255) NOT NULL DEFAULT '' COMMENT 'The filename of the eContent item if any',
  `folder` varchar(100) NOT NULL DEFAULT '' COMMENT 'A folder containing a group of files for mp-3 files',
  `acsId` varchar(128) DEFAULT NULL COMMENT 'The uid of the book within the Adobe Content Server.',
  `recordId` int(11) NOT NULL COMMENT 'The id of the record to attach the item to.',
  `item_type` enum('epub','pdf','jpg','gif','mp3','plucker','kindle','externalLink','externalMP3','interactiveBook','overdrive') NOT NULL,
  `notes` varchar(255) NOT NULL DEFAULT '',
  `addedBy` int(11) NOT NULL DEFAULT '-1' COMMENT 'The id of the user who added the item or -1 if it was added automatically',
  `date_added` longtext NOT NULL COMMENT 'The date the item was added',
  `date_updated` longtext NOT NULL COMMENT 'The last time the item was changed',
  `reviewdBy` int(11) NOT NULL DEFAULT '-1' COMMENT 'The id of the user who added the item or -1 if not reviewed',
  `reviewStatus` enum('Not Reviewed','Approved','Rejected') NOT NULL DEFAULT 'Not Reviewed',
  `reviewDate` longtext COMMENT 'When the review took place.',
  `reviewNotes` mediumtext COMMENT 'Notes about the review',
  `link` varchar(500) DEFAULT NULL,
  `libraryId` int(11) NOT NULL DEFAULT '-1',
  `overDriveId` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `RecordId` (`recordId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='EContent files that can be viewed within VuFind.';